### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by joaochris** [XMCQCX/DeviceIDPnP#1]
Hello, I'm trying to do the following: In oMyDevices.Push, I put the DeviceID of 2 devices. I want it to only execute the action when they are connected. It works. But I also wanted it to display an error when they are not connected. So I added the two separately in oMyDevices.Push, but when I pull a device it performs the action. Is there a way to do this?

**Comment by XMCQCX** [comment]
Hi, Multiple devices on the same "line" is not supported right now. I'm working on an extended version of this script that will allow to also monitor processes and windows. It will also support group of devices/processes/windows. I will release it on GitHub if I'm able to finish it. I think you can subscribe to my profile and you will be notify if I'm releasing it.

**Comment by joaochris** [comment]
Thank you for your excellent work. I can't wait, I'm subscribed :)

**Comment by XMCQCX** [comment]
> Thank you for your excellent work. I can't wait, I'm subscribed :)

I've updated DeviceIDPnP to support groups of devices and added new options. Try it out if you are interested!

**Comment by joaochris** [comment]
> > Thank you for your excellent work. I can't wait, I'm subscribed :)
> 
> I've updated DeviceIDPnP to support groups of devices and added new options. Try it out if you are interested!

Thank you very much! I haven't been able to test it yet, but I will soon :)
